[build]
# Use all available CPU cores for compilation  
# jobs = 0  # Commented out - let cargo auto-detect

[target.'cfg(all())']
# BLAS configuration for maximum performance
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3"
]

# OpenBLAS configuration
[env]
OPENBLAS_NUM_THREADS = "0"  # Use all available cores
OMP_NUM_THREADS = "0"       # For Intel MKL
MKL_NUM_THREADS = "0"       # For Intel MKL

# Specific configurations for different BLAS backends
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+avx2,+fma"]

[target.x86_64-unknown-linux-gnu]  
rustflags = ["-C", "target-feature=+avx2,+fma"] 